# Generated by Django 5.2.13 on 2026-04-17 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experiece',
            new_name='Experience',
        ),
    ]
